version: '3.8' # Versão do formato do arquivo de configuração do Docker Compose.

networks:
  vehicle-network:
    driver: bridge # Network do tipo bridge: Cria uma rede isolada em cada host, onde os contêineres podem se comunicar entre si. Todos os contêineres na mesma rede bridge podem se comunicar uns com os outros.


#volumes:
#  vehicle-vol: #Utilizado para prsistência de dados mesmo após a aplicação ser encerrada.

services:
  vehicle:
    
    build:
      context: ./app/Vehicle
      dockerfile: Dockerfile 
      image: local/vehicle:lastest # Utiliza uma imagem que está em um repositório online (DockerHub)
    
    container_name: vehicle_client
    
    env_file:
      - .env # Arquivo enviroment usado para preencher as informações de usuário, veículo e comunicação

    networks:
      - "recharging_manager"

  networks:
    recharging_manager:
      external: true
