# Repositório: macedoxx2000/vehicle:lastest

# Imagem base para a "build" da imagem atual
FROM python:3.13.2 

# Define o diretório principal
WORKDIR /app

# Copia o projeto inteiro, respeitando o .dockerignore
COPY . .

# Define os comandos e parâmetros
CMD ["python", "main.py"]